const ComponentRoutes = [
  {
    path: "/Components/Breadcrumbs",
    name: "Breadcrumbs",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Breadcrumbs"),
  },
  {
    path: "/Components/Button",
    name: "Button",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Button"),
  },
  {
    path: "/Components/Scrollbar",
    name: "Scrollbar",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Scrollbar"),
  },
  {
    path: "/Components/EmptyState",
    name: "EmptyState",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/EmptyState"),
  },
  {
    path: "/Components/Fab",
    name: "Fab",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Fab"),
  },
  {
    path: "/Components/Modal",
    name: "Modal",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Modal"),
  },
  {
    path: "/Components/Prompt",
    name: "Prompt",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Prompt"),
  },
  {
    path: "/Components/Pagination",
    name: "Pagination",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Pagination"),
  },
  {
    path: "/Components/Pulse",
    name: "Pulse",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Pulse"),
  },
  {
    path: "/Components/Tabs",
    name: "Tabs",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Tabs"),
  },
  {
    path: "/Components/Stepper",
    name: "Stepper",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Stepper"),
  },
  {
    path: "/Components/Sheet",
    name: "Sheet",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Sheet"),
  },
  {
    path: "/Components/Signature",
    name: "Signature",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Signature"),
  },
  {
    path: "/Components/Choose",
    name: "Choose",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Choose"),
  },
  {
    path: "/Components/Label",
    name: "Label",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Label"),
  },
  {
    path: "/Components/Error",
    name: "Error",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Error"),
  },
  {
    path: "/Components/Field",
    name: "Field",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Field"),
  },
  {
    path: "/Components/Input",
    name: "Input",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Input"),
  },
  {
    path: "/Components/Date",
    name: "Date",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Date"),
  },
  {
    path: "/Components/Time",
    name: "Time",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Time"),
  },
  {
    path: "/Components/Color",
    name: "Color",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Color"),
  },
  {
    path: "/Components/Spinner",
    name: "Spinner",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Spinner"),
  },
  {
    path: "/Components/Select",
    name: "Select",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Select"),
  },
  {
    path: "/Components/Textarea",
    name: "Textarea",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Textarea"),
  },
  {
    path: "/Components/FileUploader",
    name: "FileUploader",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/FileUploader"),
  },
  {
    path: "/Components/ImageUploader",
    name: "ImageUploader",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/ImageUploader"),
  },
  {
    path: "/Components/Accordion",
    name: "Accordion",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Accordion"),
  },
  {
    path: "/Components/Chip",
    name: "Chip",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Chip"),
  },
  {
    path: "/Components/Tree",
    name: "Tree",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/Tree"),
  },
  {
    path: "/Components/DataView",
    name: "DataView",
    meta: { menu: "Components" },
    component: () => import("@/pages/components-page/routes/DataView"),
  },
];

export default ComponentRoutes;
